In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the images to be in the range [0, 1]
x_train, x_test = x_train / 255.0, x_test / 255.0

# Reshape the images to have a channel dimension (28, 28, 1)
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Build a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')  # Output layer for 10 classes (digits 0-9)
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=64)

# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc}")


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


C:\Users\satvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 38s 36ms/step - accuracy: 0.8861 - loss: 0.4031
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 41s 36ms/step - accuracy: 0.9832 - loss: 0.0531
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 34s 36ms/step - accuracy: 0.9889 - loss: 0.0364
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 34s 36ms/step - accuracy: 0.9919 - loss: 0.0255
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 35s 37ms/step - accuracy: 0.9936 - loss: 0.0198
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.9843 - loss: 0.0482
Test accuracy: 0.9878000020980835


In [2]:
pip install tensorflow

   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
    --------------------------------------- 7.9/390.3 MB 40.4 MB/s eta 0:00:10
    --------------------------------------- 9.2/390.3 MB 24.8 MB/s eta 0:00:16
   - -------------------------------------- 10.5/390.3 MB 16.4 MB/s eta 0:00:24
   - -------------------------------------- 11.8/390.3 MB 13.9 MB/s eta 0:00:28
   - -------------------------------------- 14.7/390.3 MB 13.6 MB/s eta 0:00:28
   - -------------------------------------- 18.1/390.3 MB 14.1 MB/s eta 0:00:27
   -- ------------------------------------- 21.8/390.3 MB 14.5 MB/s eta 0:00:26
   -- ------------------------------------- 23.6/390.3 MB 14.0 MB/s eta 0:00:27
   -- ------------------------------------- 25.4/390.3 MB 13.3 MB/s eta 0:00:28
   -- ------------------------------------- 28.0/390.3 MB 13.1 MB/s eta 0:00:28
   --- ------------------------------------ 31.7/390.3 MB 13.2 MB/s eta 0:00:28
   --- ------------------------------------ 35.4/39

  You can safely remove it manually.
  You can safely remove it manually.


In [1]:
# Step 1: Import Libraries
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Step 2: Load the dataset
newsgroups = fetch_20newsgroups(subset='all')  # You can use 'train' or 'test' too
X = newsgroups.data  # Text data
y = newsgroups.target  # Labels (categories)

# Step 3: Preprocess and Vectorize the Text
# Use CountVectorizer to convert text into numerical form
vectorizer = CountVectorizer(stop_words='english')
X_vectorized = vectorizer.fit_transform(X)

# Step 4: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)

# Step 5: Train a classifier (Naive Bayes)
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Step 6: Predict the categories on the test set
y_pred = classifier.predict(X_test)
print(y_pred)
# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=newsgroups.target_names))


[ 9 12 14 ...  0  0 14]
Accuracy: 87.43%
Classification Report:
                          precision    recall  f1-score   support

             alt.atheism       0.85      0.91      0.88       151
           comp.graphics       0.67      0.93      0.78       202
 comp.os.ms-windows.misc       0.96      0.37      0.54       195
comp.sys.ibm.pc.hardware       0.61      0.86      0.72       183
   comp.sys.mac.hardware       0.89      0.90      0.89       205
          comp.windows.x       0.85      0.85      0.85       215
            misc.forsale       0.93      0.69      0.80       193
               rec.autos       0.91      0.95      0.93       196
         rec.motorcycles       0.95      0.94      0.95       168
      rec.sport.baseball       0.98      0.96      0.97       211
        rec.sport.hockey       0.95      0.97      0.96       198
               sci.crypt       0.92      0.96      0.94       201
         sci.electronics       0.92      0.83      0.87       202
           

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
#Importing Dataset
from keras.datasets import mnist
(train_img, train_lab), (test_img, test_lab) = mnist.load_data()

In [5]:
#Normalizing Dataset
train_img = train_img.reshape(60000, 28,28,1)
test_img = test_img.reshape(10000,28,28,1)
train_img = keras.utils.normalize(train_img, axis=1)
test_img = keras.utils.normalize(test_img, axis =1)


In [6]:
#Building Model
model=Sequential()
model.add(Conv2D(32,(3,3), input_shape=(28,28,1)))
model.add(MaxPooling2D(3,3))
model.add(Conv2D(16, (3,3)))
model.add(MaxPooling2D(3,3))
model.add(Flatten())
model.add(Dense(300, activation='relu'))
model.add(Dense(10, activation="softmax"))

C:\Users\satvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
#Compiling Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=['accuracy'])

In [8]:
#Fitting the Model
model.fit(train_img, train_lab, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 34s 16ms/step - accuracy: 0.8155 - loss: 0.5908
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 30s 16ms/step - accuracy: 0.9663 - loss: 0.1088
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 30s 16ms/step - accuracy: 0.9766 - loss: 0.0732
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 30s 16ms/step - accuracy: 0.9829 - loss: 0.0542
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.9867 - loss: 0.0431


In [9]:
#Predicting First 10 test images
pred = model.predict(test_img[:10])
# print(pred)
p=np.argmax(pred, axis=1)
print(p)
print(test_lab[:10])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step
[7 2 1 0 4 1 9 9 5 9]
[7 2 1 0 4 1 4 9 5 9]
